[package]
name = "conduit-backend-pipewire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Conduit — conduit-backend-pipewire"

[dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
conduit-core.workspace = true
conduit-backend.workspace = true
bytemuck = "1"
pipewire = { version = "0.10", features = ["v0_3_49"] }

[lints]
workspace = true
